# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JsonWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.TextField()),
                ('date_request', models.CharField(max_length=10)),
            ],
        ),
    ]
